// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDycyPiMK27o8X8wKjJhLd4U7czHwnxvNw',
    appId: '1:293618113363:web:b9398f190b6f7713a19fa6',
    messagingSenderId: '293618113363',
    projectId: 'skkullm',
    authDomain: 'skkullm.firebaseapp.com',
    storageBucket: 'skkullm.firebasestorage.app',
    measurementId: 'G-4DXV7KPWZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6YrxD6C4ZPvvifcLTU-MQZ6mnf2tEPg',
    appId: '1:293618113363:android:2a9a4fff0ed0b7d2a19fa6',
    messagingSenderId: '293618113363',
    projectId: 'skkullm',
    storageBucket: 'skkullm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSERX4Fn2nDKjooeoHu_WgMwi-ExLBN6s',
    appId: '1:293618113363:ios:29ac42b31b73e39ba19fa6',
    messagingSenderId: '293618113363',
    projectId: 'skkullm',
    storageBucket: 'skkullm.firebasestorage.app',
    iosBundleId: 'com.example.swlabSllmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSERX4Fn2nDKjooeoHu_WgMwi-ExLBN6s',
    appId: '1:293618113363:ios:29ac42b31b73e39ba19fa6',
    messagingSenderId: '293618113363',
    projectId: 'skkullm',
    storageBucket: 'skkullm.firebasestorage.app',
    iosBundleId: 'com.example.swlabSllmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDycyPiMK27o8X8wKjJhLd4U7czHwnxvNw',
    appId: '1:293618113363:web:db174c2cb9f09af4a19fa6',
    messagingSenderId: '293618113363',
    projectId: 'skkullm',
    authDomain: 'skkullm.firebaseapp.com',
    storageBucket: 'skkullm.firebasestorage.app',
    measurementId: 'G-135ZGRV0YV',
  );
}
